module.exports = [
  {
    type: 'input',
    name: 'name',
    message: 'Enter component name...',
  },
  {
    type: 'select',
    name: 'folder',
    message: 'Select screen folder...',
    choices: [
      'Auth',
      'CodeConfirm',
      'Start',
      'Main',
      'Profile',
      'Test',
      'Test',
      'Test',
      'Test',
      'Test',
      'Test',
      'Test',
      'Test2',
      'Test3',
      'Test4',
      'Test5',
      'Test5',
      'Test7',
      'Test1',
      'Test2',
      'Test3',
      'Test4',
      'Test5',
      'Test6',
      'Test7',
      'Test8',
      'Test9',
      'Test10',
      'Test11',
      'Test12',
      'Test13',
      'Test14',
      'Test15',
      'Test16',
      'Test1',
      'Test3',
      'Test3',
      'Test4',
      'Test5',
      'Test1',
      'Test2',
      'Test3',
      'Test1',
      'Test2',
      'Test1',
      'Test2',
      'Test3',
      'Test4',
      'Test5',
      'Test6',
      'Test7',
      'Test1',
      'Test1',
      'Test2',
      'Main',
      'Main',
      'Example',
      'Settings',
      'Auth',
      'Test',
      'Test2',
      'Test',
      'TestScreen',
      'TestScreen',
      'Test10',
      'Test10',
      'Persons',
      'PersonsTest',
      'Initializing',
      //ADD MORE SCREENS
    ],
  },
];
